config/routes.rb
Rails.application.routes.draw do
  resources :notes
  devise_for :users
  
  get 'home/index'
  get 'home/news'
  get 'home/weather'
  #root 'home#index'
  root 'notes#index'
  
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :user
end

app/models/note.rb
class Note < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable


        has_many :friends
        has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def weather
    @about_me = "My Name is Jack Flahive"
    require 'net/http'
    require 'json'

    #url = 'https://api.weatherbit.io/v2.0/current?lat=53.350140&lon=-6.266155&key=ff1651781b3d4a64bc2e746d57be403f&include=minutely'
    @url = 'https://api.openweathermap.org/data/2.5/weather?lat=53.350140&lon=-6.266155&appid=4ba2c6f250377c2c555b1dee609bfab4'
    #url = 'http://api.weatherapi.com/v1/forecast.json?key=c56474fb02654dcc88d140315220104&q=Dublin&days=1&aqi=no&alerts=no'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @forecast = JSON.parse(@response)




   def news
    require 'net/http'
    require 'json'

    #@url = 'https://api.weatherbit.io/v2.0/current?lat=53.350140&lon=-6.266155&key=ff1651781b3d4a64bc2e746d57be403f&include=minutely'
    @url = 'https://newsapi.org/v2/top-headlines?country=ie&apiKey=bb9bd291b5344a7b9788a0b3df5ce0f0'
    #@url = 'http://api.weatherapi.com/v1/forecast.json?key=c56474fb02654dcc88d140315220104&q=Dublin&days=1&aqi=no&alerts=no'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @news = JSON.parse(@response)
    

    




end





  end
  
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /notes or /notes.json
  def index
    @notes = Note.all
  end

  def index
    @q = Note.ransack(params[:q])
    @notes = @q.result
  end

  def flahivewordcount
    @Flahivecountwords.count_words(@body)
  end

  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
   # @note = Note.new
   @note = current_user.notes.build
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    #@note = Note.new(note_params)
    @note = current_user.notes.build(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to note_url(@note), notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to note_url(@note), notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @note = current_user.notes.find_by(id: params[:id])
    redirect_to notes_path, notice:"Not authorised" if @note.nil?

  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:title, :subtitle, :body, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">

    <%= link_to 'My App', root_path, class:"navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <li class="nav-item">

          <%= link_to "News", 
          home_news_path, 
          class:"nav-link" %>
          
        </li>

        <li class="nav-item">

          <%= link_to "Weather", 
          home_weather_path, 
          class:"nav-link" %>
          
        </li>

        

        <% if user_signed_in? %>

         <li class="nav-item">

          <%= link_to "Notes", 
          notes_path, 
          class:"nav-link" %>
          
        </li>

        <li class="nav-item">

          <%= link_to "New Note", 
          new_note_path, 
          class:"nav-link" %>
          
        </li>

         

        
        <li class="nav-item">

          <%= link_to "Edit Profile", 
          edit_user_registration_path, 
          class:"nav-link" %>
          
        </li>

        <li class="nav-item", class= "btn btn-danger">

          
          <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: "btn btn-danger"  %>
          
        </li>

        <% else %>

        
        <li class="nav-item">

          <%= link_to "Sign In", 
          new_user_session_path, 
          class:"nav-link" %>
          
        </li>

        

        <li class="nav-item">

          <%= link_to "Sign Up", 
          new_user_registration_path, 
          class:"nav-link" %>
          
        </li>

       

        

        

        <% end %>


        
        
        
      </ul>
      
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Hello World</h1>
<p>First ruby on rails webpage</p>
<p><%= button_to 'Exit', destroy_user_session_path, method: :delete %></p>

app/views/home/news.html.erb
<h1>News Updates</h1>

<div class="card">
  <h5 class="card-header">News Updates</h5>
  <div class="card-body">
    <p>
  <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseWidthExample" aria-expanded="false" aria-controls="collapseWidthExample" >
    News
  </button>
</p>
<div style="min-height: 120px;">
  <div class="collapse collapse-horizontal" id="collapseWidthExample">
    <div class="card card-body" style="width: 300px;">
      <% if @news.present? %>
   <pre><%= JSON.pretty_generate(@news) %></pre>
<% end %>
<br/>
<% if @forecast.present? %>
   <pre><%= JSON.pretty_generate(@news)  %></pre>
<% end %>
    </div>
  </div>
</div>


  </div>
</div>

app/views/home/weather.html.erb
<h1>Weather Updates</h1>


<p>


<br/>

<div class="card">
  <h5 class="card-header">Weather Updates</h5>
  <div class="card-body">
    <p>
  <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseWidthExample" aria-expanded="false" aria-controls="collapseWidthExample" >
    Weather
  </button>
</p>
<div style="min-height: 120px;">
  <div class="collapse collapse-horizontal" id="collapseWidthExample">
    <div class="card card-body" style="width: 300px;">
      <% if @forecast.present? %>
   <pre><%= JSON.pretty_generate(@forecast['weather']) %></pre>
<% end %>
<br/>
<% if @forecast.present? %>
   <pre><%= JSON.pretty_generate(@forecast['main'])  %></pre>
<% end %>
    </div>
  </div>
</div>


  </div>
</div>




     

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%=notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Hello, world!</title>

     <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
      <br/>

      <% if notice %>
      <%= render 'layouts/alerts' %>
      <% end %>
      <br/>
    <%= yield %>
  </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note) do |form| %>
  <% if note.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    
    <%= form.text_field :title, class:"form-control", placeholder:"Title" %>
  </div>

  <br/>

  <div class="field form-group">
    
    <%= form.text_field :subtitle, class:"form-control", placeholder:"Subtitle"  %>
  </div>

  <br/>

  <div class="field form-group">

    <%= form.text_area :body, class:"form-control",  placeholder:"Body" %>
    
    
    

  </div>

  <br/>



   <div>
    
    <%= form.text_field :user_id,
    id: :note_user_id, value:current_user.id, type: :hidden %>
  </div>



  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/notes/_note.html.erb
<div id="<%= dom_id note %>">
  <p>
    <strong>Title:</strong>
    <%= note.title %>
  </p>

  <p>
    <strong>Subtitle:</strong>
    <%= note.subtitle %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= note.body %>
  </p>

</div>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render "form", note: @note %>

<br>

<div>
  <%= link_to "Show this note", @note %> |
  <%= link_to "Back to notes", notes_path %>
</div>

app/views/notes/index.html.erb
<div class="container">

<div class="new">
  <div style='float: right;'>

<%= link_to "New note", new_note_path, class:"btn btn-primary btn-lg" %>

</div>

</div>
<br/>

<div class="d-flex">

    <%= search_form_for @q do |f| %>

    <%= f.search_field :title_cont %>
    <%= f.submit class: "btn btn-primary" %>
    <% end %>
</div>
<br/>


  <% @notes.each do |note| %>
  <% if note.user == current_user %>

<div class="card w-75 bg-light mb-3">
  <div class="card-body">
    <h5 class="card-title"><%= note.title %></h5>
    <p class="card-text"><%= note.subtitle %></p>
    <p class="card-text"><small class="text-muted"><%= note.created_at %></small></p>
    <%= link_to 'Show', note,  class: "btn btn-primary" %>
  </div>
</div>

<br/>


 

  

 

    <%end%>
    <%end%>
  
 







</div>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render "form", note: @note %>

<br>

<div>
  <%= link_to "Back to notes", notes_path %>
</div>

app/views/notes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @note %>


<br/>
<div>
  <%= link_to "Edit this note", edit_note_path(@note), class: "btn btn-primary" %> 
  <br/>
  <br/>
  <%= link_to "Back to notes", notes_path, class: "btn btn-light" %>
  <br/>
  <br/>

  <%= button_to "Destroy this note", @note, method: :delete, class: "btn btn-danger" %>
</div>